### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by ghost** [turbodog/rss2email#9]
```
I: Processing [1] "http://www.hoodcomputing.com/garfield.php"
I: Processing [1] "http://www.grimmy.com/RSS/todays_grimmy_cartoons.php"

=== rss2email encountered a problem with this feed ===
=== See the rss2email FAQ at http://www.allthingsrss.com/rss2email/ for assistance ===
=== If this occurs repeatedly, send this to lindsey@allthingsrss.com ===
E: could not parse http://www.hoodcomputing.com/garfield.php
Traceback (most recent call last):
 File "/Users/soulitude/bin/rss2email/rss2email.py", line 791, in run
   smtpserver = send(fromhdr, tohdr, subjecthdr, content, contenttype, extraheaders, smtpserver)
 File "/Users/soulitude/bin/rss2email/rss2email.py", line 216, in send
   smtpserver.sendmail(sender, recipient, msg_as_string)
 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 742, in sendmail
   raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {'dmz76@firemail.cc': (550, 'Delivery is not allowed to this address.')}
rss2email 2.72
feedparser 5.2.1
html2text 3.200.3
+ BeautifulSoup 3.2.1
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
=== END HERE ===
```

Happens when `FORCE_FROM = 0`.
Changing it to 1 and running r2e fixes it. But changing it back to 0 and running r2e again delivers no errors as well (!).

Error reporting by email, as instructed by rss2email failed.

```
Your message did not reach some or all of the intended recipients.

  Sent: Tue, 29 Aug 2017 14:29:57 +0100
  Subject: r2e report: Delivery is not allowed to this address

The following recipient(s) could not be reached:

lindsey@allthingsrss.com
  Error Type: SMTP
  Connection to recipients server failed.
  Error: Host name: 208.94.116.43, message: The semaphore timeout period has expired

Tried 5 time(s)

hMailServer
```

**Comment by ghost** [comment]
```
I: Processing [57] "http://www.creators.com/feeds/bc.rss"
=== rss2email encountered a problem with this feed ===
=== See the rss2email FAQ at http://www.allthingsrss.com/rss2email/ for assistance ===
=== If this occurs repeatedly, send this to lindsey@allthingsrss.com ===
E: could not parse http://www.creators.com/feeds/bc.rss
Traceback (most recent call last):
  File "/Users/soulitude/bin/rss2email/rss2email.py", line 791, in run
    smtpserver = send(fromhdr, tohdr, subjecthdr, content, contenttype, extraheaders, smtpserver)
  File "/Users/soulitude/bin/rss2email/rss2email.py", line 216, in send
    smtpserver.sendmail(sender, recipient, msg_as_string)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 748, in sendmail
    (code, resp) = self.data(msg)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 511, in data
    (code, msg) = self.getreply()
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 368, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
SMTPServerDisconnected: Connection unexpectedly closed
rss2email 2.72
feedparser 5.2.1
html2text 3.200.3
Python 2.7.13 (default, Jul 18 2017, 09:16:53) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
=== END HERE ===
```
